baseURL = "https://dudgeon.org/blog/"
languageCode = "en-us"
title = "Geoff Dudgeon"
theme = "PaperMod"
[pagination]
  pagerSize = 10

enableRobotsTXT = true

[params]
  author = "Geoff Dudgeon"
  description = "Thoughts on building with AI, product management, and making things."
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = false
  showCodeCopyButtons = true
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowAllPagesInArchive = true
  ShowFullTextinRSS = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dudgeon"

  [[params.socialIcons]]
    name = "rss"
    url = "index.xml"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
